### ISSUE TITLE
crash on mac

### ISSUE THREAD

**Issue by cgcgbcbc** [ljsimin/MinecraftJoypadSplitscreenMod#27]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 2/22/16 10:13 PM
Description: Rendering screen

java.lang.NoSuchMethodError: net.minecraft.client.gui.ScaledResolution.<init>(Lnet/minecraft/client/Minecraft;II)V
	at com.shiny.joypadmod.minecraftExtensions.JoypadControlList.drawControlButtons(JoypadControlList.java:270)
	at com.shiny.joypadmod.minecraftExtensions.JoypadControlList.drawSlot(JoypadControlList.java:248)
	at net.minecraftforge.fml.client.GuiScrollingList.drawScreen(GuiScrollingList.java:326)
	at com.shiny.joypadmod.minecraftExtensions.JoypadConfigMenu.func_73863_a(JoypadConfigMenu.java:309)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:309)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1103)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.shiny.joypadmod.minecraftExtensions.JoypadControlList.drawControlButtons(JoypadControlList.java:270)
	at com.shiny.joypadmod.minecraftExtensions.JoypadControlList.drawSlot(JoypadControlList.java:248)
	at net.minecraftforge.fml.client.GuiScrollingList.drawScreen(GuiScrollingList.java:326)
	at com.shiny.joypadmod.minecraftExtensions.JoypadConfigMenu.func_73863_a(JoypadConfigMenu.java:309)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:309)

-- Screen render details --
Details:
	Screen name: com.shiny.joypadmod.minecraftExtensions.JoypadConfigMenu
	Mouse location: Scaled: (256, 138). Absolute: (512, 203)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1103)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Mac OS X (x86_64) version 10.11.3
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 273776208 bytes (261 MB) / 533725184 bytes (509 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 1 total; -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJA	JoypadSplitscreenMod{1.7.2-0.1} [Joypad / SplitScreen Mod] (JoypadMod-1.8-0.1.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.8.14 310.42.15f01' Renderer: 'NVIDIA GeForce GT 750M OpenGL Engine'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GT 750M OpenGL Engine GL version 2.1 NVIDIA-10.8.14 310.42.15f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
```

**Comment by ahickey** [comment]
Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
JoypadSplitscreenMod{1.7.2-0.1} [Joypad / SplitScreen Mod] (JoypadMod-1.8-0.1.jar) 
Fix: need the 1.8.9 joypad mod:
http://bit.ly/1NH0VdE
